# Generated by Django 5.1.7 on 2025-04-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
