# Generated by Django 5.1.7 on 2025-05-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_rating_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='avg_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
