# Generated by Django 5.1.7 on 2025-05-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auction_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='avg_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=3),
        ),
    ]
