# Generated by Django 5.1.7 on 2025-05-14 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_auction_avg_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='avg_rating',
        ),
    ]
