# Generated by Django 5.1.7 on 2025-05-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_alter_auction_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='auction',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
